version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Europe/Berlin'
    rebase-strategy: disabled
    ignore:
      - dependency-name: '@babel/*'
        versions:
          - '>= 8'
      - dependency-name: '@types/node'
        versions:
          - '>= 25'
      - dependency-name: eslint
        versions:
          - '>= 10'
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'
          - 'browserslist'
      eslint:
        patterns:
          - '@eslint-*'
          - '@eslint/*'
          - 'eslint'
          - 'eslint-*'
      laboperator-gmbh:
        patterns:
          - '@laboperator-gmbh/*'
      markdown:
        patterns:
          - 'hast-*'
          - 'mdast-*'
          - 'micromark-*'
          - 'rehype-*'
          - 'remark-*'
          - 'unified'
          - 'unist-*'
